---
title: "Netflix Data Analysis"
output:
  pdf_document: default
  html_document: default
date: "2022-09-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Installing Libraries:



```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(naniar)
library(forcats)
library(wordcloud)
library(tm)
library(SnowballC)
library(RColorBrewer)
library(tidytext)

```

## Used head function to look at top 6 rows of data and read the data in.

```{r}
library(readxl)
netflix = read.csv("netflix_titles.csv")
head(netflix)
```
## Used glimpse for summary.

```{r}
#glimpse(netflix)
```

## Used summary for summary
```{r}
#summary(netflix)
```

## Used separate function  to split date added column intop 2 columns

```{r}
netflix = netflix %>% separate(date_added,c("date_added", "year_added"), sep = ",")
```

```{r}
netflix = netflix %>% separate(listed_in, c("Category1", "Category2", "Category3"), sep = ",")
```
### Country column analysis 


```{r}
library(dplyr)
#Check how many NA values we have in the column
netflix = netflix %>% 
  mutate(country = ifelse(country == "", NA, country ))
 netflix %>% count(is.na(netflix$country), sort = TRUE)
 
 country <- drop_na(netflix, country) 
```

## We see top countries in Netflix based on the number of movies and tv shows

```{r}
country %>% group_by(country) %>% count(country, type) %>% arrange((desc(n))) %>% head(25)
```

```{r}
ggplot(netflix, mapping=aes(x=release_year, fill = type)) + 
  geom_histogram(color="black", binmwidth = 2) + 
  labs(title = "Release by Year")
```

```{r}
netflix %>% count(is.na(netflix$country), sort = TRUE)

country_release <- drop_na(netflix, country)

country_release %>%
  count(country, sort = TRUE) %>%
  group_by(country)%>%
  head(25) %>%
  ggplot(aes(x=reorder(country, n), y=n, fill = country)) +
  geom_col(show.legend = FALSE) +
  labs(x="sum of Movues and Shows", y = "Movies and TV Shows Released", title = "top 25 countries on netflix")  +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    geom_label(aes(label=n), show.legend = FALSE) + 
    scale_y_continuous(expand = c(0,0), limits = c(0,3000))
```